name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Download ngrok
      run: |
        curl -L https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-darwin-amd64.zip -o ngrok.zip
        unzip ngrok.zip
        chmod +x ngrok
        sudo mv ngrok /usr/local/bin/ngrok
    - name: Auth
      run: ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Create Tunnel
      run: ngrok tcp 3389
